### PR TITLE
Make connectTimeout configurable

### LINKED ISSUE #43: connectTimeout is hardcoded to 1 minute
https://github.com/marcphilipp/nexus-publish-plugin/blob/master/src/main/kotlin/de/marcphilipp/gradle/nexus/internal/NexusClient.kt#L42

I'd either set it to the same value as read/write timeouts or provide a separate option.

### PR DESCRIPTION
**Pull request by slonopotamus**
Fixes #43

### CODE REVIEW

**Comment by slonopotamus** [comment]
Hmm... Something went wrong with dokka on Travis. I guess I'll remove `@see` references from NexusPublishExtension. Interestingly, It didn't prevent [build](https://travis-ci.org/marcphilipp/nexus-publish-plugin/builds/590289737) from passing.

**Review by marcphilipp — APPROVED** [review]

**Comment by marcphilipp** [comment]
Thanks! Normally I'd ask for a test but I know how hard it is to reliably simulate connection timeouts and that WireMock does not support it.

**Comment by slonopotamus** [comment]
Hmm... This could possibly be tested by creating server socket, binding it to port but not calling `accept` and then trying to connect to it. I'll try later.

**Comment by marcphilipp** [comment]
Yes, that's the only way I know about. But IIRC it doesn't work reliably on Linux because it doesn't respect the `backlog` parameter.

**Pull request merged**
